#개발환경
#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:4500/auction?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: root
#    driver-class-name: org.mariadb.jdbc.Driver
#    initialize: true
#    initialization-mode: always
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        #default_batch_fetch_size: 100
#    #open-in-view: false
#    defer-datasource-initialization: true
#
#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page_size: 2000
#        #one-indexed-parameters: true
#
#  profiles:
#    include: oauth
#  session:
#    store-type: jdbc
#
#  redis:
#    host: localhost
#    port: 6379
#
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
#
#jwt:
#  header: Authorization
#  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
#  token-validity-in-seconds: 86400

## 운영용
spring:
  datasource:
    url: jdbc:mariadb://localhost:4500/auction?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #default_batch_fetch_size: 100
    #open-in-view: false

  data:
    web:
      pageable:
        default-page-size: 10
        max-page_size: 2000
        #one-indexed-parameters: true

  profiles:
    include: oauth
  session:
    store-type: jdbc

  redis:
    host: redis
    port: 6379

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400



