spring:
  profiles:
    active: prod

---

spring:
  profiles: dev
  session:
    store-type: jdbc
  datasource:
    url: ENC(3SqkO9opA57zKvYvMvimruQNEJEjV9V8z7tI9NUCAY3OGjwsVThPldxFCgASHqBaozAknibyoxipHwZo3WbmikXrvkgyk0vqVNgX3ddT+kpMqam1vXDUig==)
    username: ENC(/lVE+C9aOThU0R+5svbX4w==)
    password: ENC(JzeeGqZ3GE8GTOFeoiTTmg==)
    driver-class-name: org.mariadb.jdbc.Driver
  #    initialize: true
  #    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #default_batch_fetch_size: 100
    #open-in-view: false
  #    defer-datasource-initialization: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page_size: 2000
        #one-indexed-parameters: true

  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(PnBMXKZDGWhSo48lvPRhW9pDGEg68ny9bVioHhha+Pp3iNL0JGorh5KaGTFDpXdvTCS76zebiIpyv3gpIfMJQkGnSu3ibra1OzIcpQ1BzG7Jc1RB+XPSTw==)
        provider:
          google:
            issuer-uri: https://accounts.google.com
          kakao:
            user-info-uri: https://kapi.kakao.com/v2/user/me
          naver:
            user-info-uri: https://openapi.naver.com/v1/nid/me

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 60000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465

AdminMail:
  id: ENC(hUhy2YDKe6zfK2L0wQ+WjUX3WI2L66FnAArFJFuJrhTFfxPcdxFAzQ==)
  password: ENC(q0+Ds0DGrBF6GUQZ/Qg/ex0FQC/nGqyi)

firebase:
  api:
    url: ENC(42Gg0U+BcNEE9NeimlwGMbmJ2Cwkgsozk0q/zFSIh15TVp+AQ5y08KpovLr7kcOg8OBpv3QNaPhc1Ip/EAaNBIxOSoF37crgpafJc1XQ9xw=)
  image:
    api:
      url: ENC(2rZc7kDMp+pQGny5hInr3ALqLNKZJyiGymyKmUmKIdPTpGiELbfldnP/zGEXa5BgnkjPsTIyllQ8qu73y84UN/Q3BcbpZS1CHe63OSpqAc/0d/v+GyuzUT0qP5+IqBRxkYkqhs0tqsjD4EWypvJPnID7Kl9BmxhkwAIG+ZWxc803Qq20myE8GrM6sXRUHaj9lMveXJv5Oeo=)
  google:
    credentials:
      api:
        url: ENC(7Q7g4eiRP2a9Ee+/r7nrS74BxpHujwXlZml5Wqkug7MYoK+7ppKMdB4eRHYDEeWChiHFFTNrhHc=)

---

spring:
  profiles: prod
  session:
    store-type: jdbc
  datasource:
    url: ENC(3SqkO9opA57zKvYvMvimruQNEJEjV9V8z7tI9NUCAY3OGjwsVThPldxFCgASHqBaozAknibyoxipHwZo3WbmikXrvkgyk0vqVNgX3ddT+kpMqam1vXDUig==)
    username: ENC(/lVE+C9aOThU0R+5svbX4w==)
    password: ENC(JzeeGqZ3GE8GTOFeoiTTmg==)
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #default_batch_fetch_size: 100
    #open-in-view: false

  data:
    web:
      pageable:
        default-page-size: 10
        max-page_size: 2000
        #one-indexed-parameters: true

  redis:
    host: redis
    port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(PnBMXKZDGWhSo48lvPRhW9pDGEg68ny9bVioHhha+Pp3iNL0JGorh5KaGTFDpXdvTCS76zebiIpyv3gpIfMJQkGnSu3ibra1OzIcpQ1BzG7Jc1RB+XPSTw==)
        provider:
          google:
            issuer-uri: https://accounts.google.com
          kakao:
            user-info-uri: https://kapi.kakao.com/v2/user/me
          naver:
            user-info-uri: https://openapi.naver.com/v1/nid/me

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 60000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

mail:
  smtp:
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    port: 465

AdminMail:
  id: ENC(hUhy2YDKe6zfK2L0wQ+WjUX3WI2L66FnAArFJFuJrhTFfxPcdxFAzQ==)
  password: ENC(q0+Ds0DGrBF6GUQZ/Qg/ex0FQC/nGqyi)

firebase:
  api:
    url: ENC(42Gg0U+BcNEE9NeimlwGMbmJ2Cwkgsozk0q/zFSIh15TVp+AQ5y08KpovLr7kcOg8OBpv3QNaPhc1Ip/EAaNBIxOSoF37crgpafJc1XQ9xw=)
  image:
    api:
      url: ENC(2rZc7kDMp+pQGny5hInr3ALqLNKZJyiGymyKmUmKIdPTpGiELbfldnP/zGEXa5BgnkjPsTIyllQ8qu73y84UN/Q3BcbpZS1CHe63OSpqAc/0d/v+GyuzUT0qP5+IqBRxkYkqhs0tqsjD4EWypvJPnID7Kl9BmxhkwAIG+ZWxc803Qq20myE8GrM6sXRUHaj9lMveXJv5Oeo=)
  google:
    credentials:
      api:
        url: ENC(7Q7g4eiRP2a9Ee+/r7nrS74BxpHujwXlZml5Wqkug7MYoK+7ppKMdB4eRHYDEeWChiHFFTNrhHc=)
