spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:4500/auction?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #default_batch_fetch_size: 100
    #open-in-view: false

  data:
    web:
      pageable:
        default-page-size: 10
        max-page_size: 2000
        #one-indexed-parameters: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
