#개발환경
#spring:
#  datasource:
#    url: ENC(3SqkO9opA57zKvYvMvimruQNEJEjV9V8z7tI9NUCAY3OGjwsVThPldxFCgASHqBaozAknibyoxipHwZo3WbmikXrvkgyk0vqVNgX3ddT+kpMqam1vXDUig==)
#    username: ENC(/lVE+C9aOThU0R+5svbX4w==)
#    password: ENC(JzeeGqZ3GE8GTOFeoiTTmg==)
#    driver-class-name: org.mariadb.jdbc.Driver
#    initialize: true
#    initialization-mode: always
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        #default_batch_fetch_size: 100
#    #open-in-view: false
#    defer-datasource-initialization: true
#
#  data:
#    web:
#      pageable:
#        default-page-size: 10
#        max-page_size: 2000
#        #one-indexed-parameters: true
#
#  profiles:
#    include: oauth
#  session:
#    store-type: jdbc
#
#  redis:
#    host: localhost
#    port: 6379
#
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
#
#jwt:
#  header: Authorization
#  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
#  token-validity-in-seconds: 86400
#
#jasypt:
#  encryptor:
#    bean: jasyptStringEncryptor
#
#resources:
#  location: /C:/Users/KIMJUNGWOO/Desktop/JUNGWOO/tempimages/
#  uri_path: /api/v1/files

# 운영용
spring:
  datasource:
    url: ENC(3SqkO9opA57zKvYvMvimruQNEJEjV9V8z7tI9NUCAY3OGjwsVThPldxFCgASHqBaozAknibyoxipHwZo3WbmikXrvkgyk0vqVNgX3ddT+kpMqam1vXDUig==)
    username: ENC(/lVE+C9aOThU0R+5svbX4w==)
    password: ENC(JzeeGqZ3GE8GTOFeoiTTmg==)
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #default_batch_fetch_size: 100
    #open-in-view: false

  data:
    web:
      pageable:
        default-page-size: 10
        max-page_size: 2000
        #one-indexed-parameters: true

  profiles:
    include: oauth
  session:
    store-type: jdbc

  redis:
    host: redis
    port: 6379

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

resources:
  location: /home/ec2-user/hup/images/
#  uri_path: /api/v1/files



