INSERT INTO user (USER_ID, LOGIN_ID, EMAIL, USERNAME, PASSWORD, PHONE_NUMBER, ACTIVATED, EMAIL_AUTH_ACTIVATED, PICTURE) VALUES (100, 'admin', 'admin@naver.com', 'adminName',
'$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', '010-1111-1111', 1, 1, "PICTURE");

INSERT INTO authority (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO authority (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO user_authority (USER_ID, AUTHORITY_NAME) values (100, 'ROLE_USER');
INSERT INTO user_authority (USER_ID, AUTHORITY_NAME) values (100, 'ROLE_ADMIN');

