INSERT INTO USER (USER_ID, LOGIN_ID, EMAIL, USERNAME, PASSWORD, PHONE_NUMBER, ACTIVATED, EMAIL_AUTH_ACTIVATED, PICTURE) VALUES (100, 'admin', 'admin@naver.com', 'adminName',
'admin12345', '010-1111-1111', 1, 1, "PICTURE");

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (100, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (100, 'ROLE_ADMIN');